### ISSUE TITLE
Compilation Error for invoking `create_lobby` and `list_lobby`

### ISSUE THREAD

**Issue by TheYellowArchitect** [blazium-engine/blazium-lobby-sdk#7]
Inside the class `user.gd`
![lobby1](https://github.com/user-attachments/assets/392572e0-d433-4c8c-b34c-c52d854bd10c)
![lobby2](https://github.com/user-attachments/assets/4341419a-1c75-44c3-b13b-1900a672b1d0)

The first error above is easily solved by deleting "Title"
The second error has a problem because `lobby` is a String, so it has no properties to display.

Blazium Editor Version: Built with `785082e47837806c63fa959b688c6afe8ace72d2`
Blazium Lobby Editor: Cloned from `507a6db8c28b1bffa81886e653d1f9cb57883df0`

**Comment by Ughuuu** [comment]
If you want a working version, for now until I merge a fix you can try running the https://github.com/blazium-engine/blazium/pull/158 PR. This updates after the updated service.

**Comment by TheYellowArchitect** [comment]
Not just working but something I can tweak and build a very very simple game upon. I can wait for a hangman if it comes soon, no worries. The only reason I want to test this is because the sooner i get something to work on, the sooner I can make a video on these online services - and ofc I don't want any bugs because then my coverage will be outdated/rushed.

**Comment by Ughuuu** [comment]
Should be fixed now. This issue can be closed. If you want to follow the development of the hangman, you can follow that here: https://github.com/blazium-engine/example-game-hangman/issues/1

**Comment by Bioblaze** [comment]
This has been complete
